name: Deploy application

on:
  push:
    branches:
      - main
env:
  PUCLIC_BASE_URL: ${{ vars.PUCLIC_BASE_URL }}
  PUCLIC_MY_TWITTER_URL: ${{ vars.PUCLIC_MY_TWITTER_URL }}
  PUCLIC_MY_GITHUB_URL: ${{ vars.PUCLIC_MY_GITHUB_URL }}
  PUCLIC_MY_LINKEDIN_URL: ${{ vars.PUCLIC_MY_LINKEDIN_URL }}
  PUCLIC_MY_EMAIL: ${{ vars.PUCLIC_MY_EMAIL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxdamage1 \
            libxfixes3 libxrandr2 libgbm1 libasound2 libpangocairo-1.0-0 \
            libpango-1.0-0 libcairo2 libatspi2.0-0
      - name: Install modules
        run: yarn
      - name: Build application
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
        run: yarn build
      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://${{ secrets.BUCKET_ID }}
      - name: Invalidate cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUITION_ID }} --paths "/*"
